### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by X-n3t** [s4vitar/btcAnalyzer#1]
Siguiendo tu explicación del video piqué tu código a mano, he preferido dar otro orden al menú, las tablas me salen con otro aspecto(con tu script me pasa igual).
Estas dejando de ser tikis mikis, no me gusta esta salida con el -h: (btcAnalyzer.sh.1: la opción requiere un argumento -- h), lo he arreglado haciendo una chapucilla.
En la suma cambie los puntos por comas, para mantener el formato de la tabla, si no vaya locura.
Gracias por compartir, siempre se aprende.
![imagen](https://user-images.githubusercontent.com/52056830/89827017-5dc43980-db57-11ea-8aeb-84ac9f06370b.png)

**Comment by X-n3t** [comment]
Me tome la libertad de sacar una version que amplia compatibilidad con distros basadas en Arch, ya que hay un problemilla con html2text:
https://github.com/X-n3t/bash/blob/master/btcAnalyzer/btcAnalyzer2.sh
![Screenshot_20200811_125840](https://user-images.githubusercontent.com/52056830/89890224-47f45a00-dbd3-11ea-90b7-cb323e8e09ef.png)
version 2.1
![imagen](https://user-images.githubusercontent.com/52056830/89924112-d8499380-dc01-11ea-8a27-58c174a97d43.png)

**Comment by s4vitar** [comment]
¡Buen trabajo!, lo dicho, cualquier cambio o mejor que se quiera implementar a por ello.
